### ISSUE TITLE
Brak danych

### ISSUE THREAD

**Issue by Nowosad** [blakos1/spcomparison#2]
Nie mogę odtworzyć kodu results bo brakuje data/2classes_dist.csv i data/3classes_dist.csv.

**Comment by blakos1** [comment]
Dane powinny utworzyć się po uruchomieniu 2classes.R i 3classes.R (sam koniec kodu) - można w linii 145 dla 2classes i 119 dla 3classes ograniczyć ilość metod do obliczenia żeby obliczyło się szybciej.

**Comment by Nowosad** [comment]
Niech Pan je wrzuci do data (będzie szybciej:))

**Comment by blakos1** [comment]
Zrobione
